### ISSUE TITLE
conform sections

### ISSUE THREAD

**Issue by daga2** [HL7/C-CDA-Examples#13]
These examples seem to be very inconsistent when including the templateId of Conforms parts.

as an example
https://github.com/HL7/C-CDA-Examples/blob/master/Allergies/No%20Known%20Allergies/No%20Known%20Allergies%20with%20Author%20Timestamp(C-CDA2.1).xml

The section Allergies and Intolerances Section (entries required) (V3) does not conform properly to 
Allergies and Intolerances Section (entries optional) (V3).  There is no templateId with a root of 2.16.840.1.113883.10.20.22.2.6.1 which appears to be required by CONF:1198-10379.

The following example does include the templateId, but I don't understand why one example does and one example does not include this templateId.

https://github.com/HL7/C-CDA-Examples/blob/master/Allergies/No%20Section%20Information%20Allergies/No%20Information%20Allergies(C-CDA2.1).xml

**Comment by brettmarquard** [comment]
Please update your user name so we know who you are!

As a general rule, best practice is to include the 'conforms to' template but it's not required.
