### ISSUE TITLE
Do not use special characters in in readme files

### ISSUE THREAD

**Issue by astechishin** [HL7/C-CDA-Examples#5]
The readme: https://raw.githubusercontent.com/HL7/C-CDA-Examples/master/Header/Patient%20Demographic%20Information/Readme.md contains non-printing characters. Pasting from Word or Excel will inject non-printing characters specific to Windows into text and causes issues on Unix based systems. (review comment section)

**Comment by brettmarquard** [comment]
Updated.

-Is there a way to fail gracefully if other users include?

**Comment by brettmarquard** [comment]
I will take that as a no.
